### ISSUE TITLE
No test_project file found

### ISSUE THREAD

**Issue by apacha** [bitrise-steplib/steps-xamarin-android-test#11]
I've tried to get this step up and running, but unfortunately, I'm only getting the following exception in this step:

> +------------------------------------------------------------------------------+
> | (1) xamarin-android-test@0.9.1                                               |
> +------------------------------------------------------------------------------+
> | id: xamarin-android-test                                                     |
> | version: 0.9.1                                                               |
> | collection: https://github.com/bitrise-io/bitrise-steplib.git                |
> | time: 2016-03-26T09:34:27-07:00                                              |
> +------------------------------------------------------------------------------+
> |                                                                              |
> ==> Performing step
> No test_project file found
> ERRO[09:34:31] Step (xamarin-android-test@0.9.1) failed, error: (exit status 1) 
> |                                                                              |
> +----+--------------------------------------------------------------+----------+
> | 🚫  | xamarin-android-test@0.9.1 (exit code: 1)                    | 5.4 sec  |
> +----+--------------------------------------------------------------+----------+
> | Issue tracker: ...thub.com/bitrise-steplib/steps-xamarin-android-test/issues |
> | Source: https://github.com/bitrise-steplib/steps-xamarin-android-test        |
> +----+--------------------------------------------------------------+----------+

I've followed these [instruction from the tutorial](http://blog.bitrise.io/2016/03/05/xamarin-ci-with-bitrise-tutorial-part-2-testing.html), but specifically at the point where it comes down to setting up the step in Bitrise, it simply states:

> Now you just have to add the Xamarin Android Test step to your workflow.

It is not obvious what is wrong here, since I've tried to add several different paths into the configuration of `Path to Xamarin UITest Project` of this step, including the path to the solution, path to the .csproj of the tests and also leaving it empty. What is this mysterious test_project file and where do I have to add it? And btw: I get the very same message when using the `xamarin-ios-test` step

**Comment by birmacher** [comment]
Hi @apacha!

Can you invite the `xamarin-support` user to your project on Bitrise and I'll take a look.

**Comment by apacha** [comment]
Still has access. Just log in.

**Comment by Dids** [comment]
Any news on this?

EDIT: Never mind, had to set the relative directory path, so in my case I entered `UITest`, which was enough. Now I'm getting `emulator_serial not specified` though.

**Comment by Dids** [comment]
Actually, I'm not seeing `$BITRISE_EMULATOR_SERIAL` being applied to `emulator_serial` anywhere, so this plugin can't work at all, right?

**Comment by godrei** [comment]
Hi @apacha and @Dids ,
sorry for my late response!

__This step is no longer maintained.__

bitrise runs your builds in virtual machines, to run virtual machines on a physical device, it uses hardare virtualization.

Because of this, on vms we can not use x86 emulator images, nor x86 image +  Hardware Accelerated Execution Manager (HAXM) to speed up the emulators.

The armeabi emulators are really slow, thats why we can not run stable tests, even with our minimal sample app with increased `WaitTimes` in the UItest project.

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!

**Comment by viktorbenei** [comment]
Just to clarify:

> The armeabi emulators are really slow, thats why we can not run stable tests, even with our minimal sample app with increased WaitTimes in the UItest project.

This is related to __this step__ and __the tools this step used__. It's certainly possible to run reliable tests even in ARM simulators, just not with this step (part of why this was deprecated).

**Comment by godrei** [comment]
Hi guys,
we shared a new version of this step ([1.0.0](https://github.com/bitrise-steplib/steps-xamarin-android-test/releases/tag/1.0.0)), this contains major fixes and updates. Please read the step description and the input descriptions for proper setup.

Also we [separated the Start Android Emulator step](https://discuss.bitrise.io/t/wait-for-android-emulator-step-v0-9-0-released/779), to speed up the builds using android emulator.

The changes in this step and around the emulator handling leaded to stable tests.
