### ISSUE TITLE
Incorrect test file selected by NUnit

### ISSUE THREAD

**Issue by gtsmt** [bitrise-steplib/steps-xamarin-android-test#14]
Hi guys,
There is an issue in the step that nunit runner will take first file from /bin/ directory after built of UITest project. If your UITest output assembly has lower letter than "n" it will not be selected for further processing. As a workaround you have change assembly output name for example for: AAA.UITestProject.dll.

Example output for incorrect run:

> Build succeeded.
> 	 0 Warning(s)
> 	 0 Error(s)
> 
> Time Elapsed 00:02:05.2420170
>   (i) .dll path: /Users/vagrant/git/MobileTest/UISample/UITests/bin/AnyCPU/Debug/nunit.framework.dll
> 
> => run unit test
> NUnit Console Runner 3.4.1 
> Copyright (C) 2016 Charlie Poole
> 
> Runtime Environment
>    OS Version: MacOSX 16.3.0.0 
>   CLR Version: 4.0.30319.42000
> 
> Test Files
>     /Users/vagrant/git/MobileTest/UISample/UITests/bin/AnyCPU/Debug/nunit.framework.dll
> 
> 
> Errors and Failures
> 
> 1) Invalid : /Users/vagrant/git/MobileTest/UISample/UITests/bin/AnyCPU/Debug/nunit.framework.dll
> WARNING: The runtime version supported by this application is unavailable.
> Using default runtime: v4.0.30319
> No suitable tests found in '/Users/vagrant/git/MobileTest/UISample/UITests/bin/AnyCPU/Debug/nunit.framework.dll'.
> Either assembly contains no tests or proper test driver has not been found.
> 
> Test Run Summary
>   Overall result: Failed
>   Test Count: 0, Passed: 0, Failed: 0, Inconclusive: 0, Skipped: 0
>   Start time: 2017-02-03 13:53:12Z
>     End time: 2017-02-03 13:53:12Z
>     Duration: 0.008 seconds
> 
> Results (nunit3) saved as TestResult.xml
> 
> result: ﻿<?xml version="1.0" encoding="utf-8" standalone="no"?>
> <test-run id="2" testcasecount="0" result="Failed" label="Invalid" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0" engine-version="3.4.1.0" clr-version="4.0.30319.42000" start-time="2017-02-03 13:53:12Z" end-time="2017-02-03 13:53:12Z" duration="0.008413">
>   <command-line><![CDATA[/Users/vagrant/bitrise/xamarin/nunit/3.4.1/bin/nunit3-console.exe /Users/vagrant/git/MobileTest/UISample/UITests/bin/AnyCPU/Debug/nunit.framework.dll]]></command-line>
>   <test-suite type="Assembly" id="0-1" name="nunit.framework.dll" fullname="/Users/vagrant/git/MobileTest/UISample/UITests/bin/AnyCPU/Debug/nunit.framework.dll" testcasecount="0" runstate="NotRunnable" result="Failed" label="Invalid">
>     <properties>
>       <property name="_SKIPREASON" value="No suitable tests found in '/Users/vagrant/git/MobileTest/UISample/UITests/bin/AnyCPU/Debug/nunit.framework.dll'.
> Either assembly contains no tests or proper test driver has not been found." />
>     </properties>
>     <reason>
>       <message>No suitable tests found in '/Users/vagrant/git/MobileTest/UISample/UITests/bin/AnyCPU/Debug/nunit.framework.dll'.
> Either assembly contains no tests or proper test driver has not been found.</message>
>     </reason>
>   </test-suite>
> </test-run>
> 
> /Library/Frameworks/Mono.framework/Versions/Current/bin/mono /Users/vagrant/bitrise/xamarin/nunit/3.4.1/bin/nunit3-console.exe /Users/vagrant/git/MobileTest/UISample/UITests/bin/AnyCPU/Debug/nunit.framework.dll -- failed
> |

**Comment by godrei** [comment]
Hi @gtsmt ,
could you please move this issue to the `NUnit runner` step's [issues](https://github.com/bitrise-steplib/steps-nunit-runner/issues), since this report is not related to this step.
