### ISSUE TITLE
Error: No project to build found

### ISSUE THREAD

**Issue by merikwesterveld** [bitrise-steplib/steps-xamarin-android-test#27]
In my project, I have setup Xamarin UI tests and want to run those tests in Bitrise. Therefore in my workflow, I run a avd-manager to boot a android simulator and after the booting I placed the Xamarin Android Test module. I haven't configured anything in this module so it should by default run all tests. However I get the following error message:

Test project (Testin.Xamarin.UITests) does not refers to any project, with project type whitelist ([android]), skipping...
Build failed, error: No project to build found

Is this a bug or how can I fix this?

**Comment by Roland-Bak** [comment]
Hey @merikwesterveld , same here :)
Please send us the URL of the build and enable Support Access, and we'll take a look! ;)

**Comment by merikwesterveld** [comment]
@Roland-Bak  

https://app.bitrise.io/build/cd0afbfc15b837f0#?tab=log 

This one?
Thanks!

**Comment by Roland-Bak** [comment]
Hey there, thanks for your patience!

Could you try adding` add <!-- Include="nunit.framework" -->` line somewhere in your Unit-Test csproj file?

**Comment by FabianClaasenWhyellow** [comment]
@Roland-Bak 

We tried adding the line to our project file, but with no success.

**Comment by Roland-Bak** [comment]
Hi @FabianClaasenWhyellow , sorry for the confusion!

What I meant to say is to find `Include="nunit.framework"` in your csproj file (it should already be there), and comment it out so it is ignored 🙂
So please remove ` add <!-- Include="nunit.framework" -->` if you have added it, find `Include="nunit.framework"` and changed to this: `
`
(In case you can't find it, please add it yourself, as it could be something that is included by default)

Let me know if this advances your issue 😉
